apiVersion: v2
name: searchingest
description: A PlaceOS helm chart for the Rubber-Soul component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-2.2310.1
