# xrethinkdbPassword the admin password for RethinkDb.
#  Used to set the admin password in RethinkDB if enabled then passed to multiple containers in a k8s secret
xrethinkdbPassword: &rethinkdbPassword "{{ rethinkdbPassword }}"

#  Used to set the postgres user password in PostgresQL if enabled then passed to multiple containers in a k8s secret
xpostgresqlPassword: &postgresqlPassword "{{ postgresqlPassword }}"

# xsmtpPassword. the smtp password used by triggers
xsmtpPassword: &smtpPassword "{{ smtpPassword | default( '', true ) }}"

# xplacePassword. The value used by the init subchart to set the default domain users password
xplacePassword: &placePassword "{{ placePassword | default( '', true ) }}"

# xplaceServerSecret for the placeos service
xplaceServerSecret: &placeServerSecret "{{ placeServerSecret | default( '', true ) }}"

# xserverSecret for the dispatch service
xserverSecret: &serverSecret "{{ serverSecret | default( '', true ) }}"

# xelasticClientEnv configmap values for ElasticSearch Service exposed as environment variables to PlaceOS containers
xelasticClientEnv: &elasticClientEnv
  ES_HOST: "{{ elasticsearch_release_name }}-elasticsearch-master.{{ elasticsearch_namespace }}"
  ES_PORT: 9200

# xetcdClientEnv configmap values for Etcd end point Service as environment variables to PlaceOS containers
xetcdClientEnv: &etcdClientEnv
  ETCD_HOST: "etcd-headless.{{ etcd_namespace }}"
  ETCD_PORT: 2379

# xredisClientEnv configmap values for the redis Service exposed as environment variables to PlaceOS containers
xredisClientEnv: &redisClientEnv
  REDIS_URL: "redis://redis-headless.{{ redis_namespace }}:6379"

# xrethinkdbClientEnv configmap values for RethinkDB Service exposed as environment variables to PlaceOS containers
xrethinkdbClientEnv: &rethinkdbClientEnv
  RETHINKDB_HOST: "{{ rethinkdb_release_name }}-rethinkdb-proxy.{{ rethinkdb_namespace }}"
  RETHINKDB_PORT: 28015
  RETHINKDB_DB: place_development
  RETHINKDB_USER: admin

xrethinkdbClientSecrets: &rethinkdbClientSecrets
  RETHINKDB_PASSWORD: *rethinkdbPassword

xpostgresqlValues: &postgresqlValues
  postgresqlUsername: placeos
  postgresqlDatabase: placeos
  postgresqlPassword: *postgresqlPassword

# xsmtpClientSecrets secrets values exposed as environment variables for the trigger service
xsmtpClientSecrets: &smtpClientSecrets
  SMTP_PASS: *smtpPassword

# dispatchSecrets secret values exposed as environment variables for the dispatch service
xdispatchSecrets: &dispatchSecrets
  SERVER_SECRET: *serverSecret

placeos:
  enabled: true
  # api is the overide configuration for the embedded api subchart
  api:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
    configmap:
      # Service Hosts
      << : *elasticClientEnv
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # auth is the overide configuration for the embedded auth subchart
  auth:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
    configmap:
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # core is the overide configuration for the embedded core subchart
  core:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # dispatch is the overide configuration for the embedded dispatch subchart
  dispatch:
    udpLoadbalancer:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
    tcpLoadbalancer:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
    secrets:
      << : *dispatchSecrets
  # frontend-loader is the overide configuration for the embedded frontend-loader subchart
  frontend-loader:
    httpSidecar: false
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/app-root: "/backoffice/"
    configmap:
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # search-ingest is the overide configuration for the embedded search-ingest subchart
  search-ingest:
    configmap:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # triggers is the overide configuration for the embedded triggers subchart
  triggers:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      << : *smtpClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # init is the overide configuration for the embedded init subchart
  init:
    config:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
      << : *rethinkdbClientSecrets
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
  # staff is the overide configuration for the embedded staff subchart
  staff:
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
    << : *postgresqlValues
  global:
    placeDomain: "{{ placeDomain | default('localhost', true ) }}"
    customRedirectPort: "{{ customRedirectPort | default( omit ) }}"
    gcpbackendConfig:
      enabled: true
      name: placeos-core
      config:
        connectionDraining:
          drainingTimeoutSec: 60
        securityPolicy:
          name: "cloudarmor-policy"
      global_static_ip_name: "l7-ip"
      loadbalancerAccessType: "External"

###########################################
##### Third Party Supporting Services #####
###########################################

ingress-nginx:
  enabled: false
  fullnameOverride: "ingress-nginx"
etcd:
  fullnameOverride: etcd
  enabled: true
  auth:
    rbac:
      enabled: false
elasticsearch:
  enabled: true
  master:
    replicas: 1
  data:
    replicas: 1
  coordinating:
    replicas: 0
rethinkdb:
  enabled: true
  cluster:
    replicas: 1
  rethinkdbPassword: "{{ rethinkdbPassword }}"
redis:
  fullnameOverride: redis
  enabled: true
  usePassword: false
  cluster:
    enabled: false
influxdb:
  fullnameOverride: influxdb
  enabled: false
mosquitto:
  enabled: false
  fullnameOverride: mosquitto
postgresql:
  enabled: true
  fullnameOverride: postgresql
  << : *postgresqlValues
