#Domain variables set for a local install
placeDomain: "localhost"
customRedirectPort: 8443

# xrethinkdbPassword the admin password for RethinkDb.
#  Used to set the admin password in RethinkDB if enabled then passed to multiple containers in a k8s secret
xrethinkdbPassword: &rethinkdbPassword "{{ rethinkdbPassword }}"

#  Used to set the postgres user password in PostgresQL if enabled then passed to multiple containers in a k8s secret
xpostgresqlPassword: &postgresqlPassword "{{ postgresqlPassword }}"

# xsmtpPassword. the smtp password used by triggers
xsmtpPassword: &smtpPassword "{{ smtpPassword | default( '', true ) }}"

# xplaceServerSecret for the placeos service
xplaceServerSecret: &placeServerSecret "{{ placeServerSecret | default( '', true ) }}"

# xplaceServerSecret for the placeos service
xauthSecretKeyBase: &authSecretKeyBase "{{ authSecretKeyBase | default( '', true ) }}"

# xplacePassword. The value used by the init subchart to set the default domain users password
xplacePassword: &placePassword "{{ placePassword | default( '', true ) }}"

# xserverSecret for the dispatch service
xserverSecret: &serverSecret "{{ serverSecret | default( '', true ) }}"

# xelasticClientEnv configmap values for ElasticSearch Service exposed as environment variables to PlaceOS containers
xelasticClientEnv: &elasticClientEnv
  ES_HOST: "{{ elasticsearch_release_name }}.{{ elasticsearch_namespace }}"
  ES_PORT: 9200

# xetcdClientEnv configmap values for Etcd end point Service as environment variables to PlaceOS containers
xetcdClientEnv: &etcdClientEnv
  ETCD_HOST: "etcd-headless.{{ etcd_namespace }}"
  ETCD_PORT: 2379

# xredisClientEnv configmap values for the redis Service exposed as environment variables to PlaceOS containers
xredisClientEnv: &redisClientEnv
  REDIS_URL: "redis://redis-headless.{{ redis_namespace }}:6379"

# xrethinkdbClientEnv configmap values for RethinkDB Service exposed as environment variables to PlaceOS containers
xrethinkdbClientEnv: &rethinkdbClientEnv
  RETHINKDB_HOST: "{{ rethinkdb_release_name }}-rethinkdb-proxy.{{ rethinkdb_namespace }}"
  RETHINKDB_PORT: 28015
  RETHINKDB_DB: place_development
  RETHINKDB_USER: admin

xrethinkdbClientSecrets: &rethinkdbClientSecrets
  RETHINKDB_PASSWORD: *rethinkdbPassword

xpostgresqlValues: &postgresqlValues
  global:
    postgresql:
      auth:
        username: placeos
        database: placeos
        password: *postgresqlPassword
        postgresPassword: *postgresqlPassword

# xsmtpClientSecrets secrets values exposed as environment variables for the trigger service
xsmtpClientSecrets: &smtpClientSecrets
  SMTP_PASS: *smtpPassword

# dispatchSecrets secret values exposed as environment variables for the dispatch service
xdispatchSecrets: &dispatchSecrets
  SERVER_SECRET: *serverSecret

placeos:
  enabled: true
  # api is the overide configuration for the embedded api subchart
  api:
    configmap:
      # Service Hosts
      << : *elasticClientEnv
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # auth is the overide configuration for the embedded auth subchart
  auth:
    configmap:
      << : *rethinkdbClientEnv
    secrets:
      SECRET_KEY_BASE: *authSecretKeyBase
      << : *rethinkdbClientSecrets
  # core is the overide configuration for the embedded core subchart
  core:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # dispatch is the overide configuration for the embedded dispatch subchart
  dispatch:
    secrets:
      << : *dispatchSecrets
  # frontend-loader is the overide configuration for the embedded frontend-loader subchart
  frontendloader:
    httpSidecar: true
    configmap:
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # search-ingest is the overide configuration for the embedded search-ingest subchart
  searchingest:
    configmap:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # triggers is the overide configuration for the embedded triggers subchart
  triggers:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      << : *smtpClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # init is the overide configuration for the embedded init subchart
  init:
    config:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
      << : *rethinkdbClientSecrets
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
  # staff is the overide configuration for the embedded staff subchart
  staff:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
    << : *postgresqlValues
  global:
    placeDomain: "{{ placeDomain }}"
    customRedirectPort: "{{ customRedirectPort | default( omit ) }}"

###########################################
##### Third Party Supporting Services #####
###########################################

ingress-nginx:
  enabled: false
etcd:
  fullnameOverride: etcd
  enabled: true
  auth:
    rbac:
      enabled: false
  persistence.size: 100Mib
elasticsearch:
  enabled: true
  master:
    replicas: 1
    persistence:
      size: 100Mib
  data:
    replicas: 1
    persistence:
      size: 100Mib
  coordinating:
    replicas: 0
rethinkdb:
  enabled: true
  cluster:
    replicas: 1
  rethinkdbPassword: "{{ rethinkdbPassword }}"
redis:
  enabled: true
  fullnameOverride: redis
  auth:
    enabled: false
  architecture: standalone
  commonConfiguration: |-
    notify-keyspace-events Kg$
  master:
    persistence:
      enabled: true
      size: 1Gi
influxdb:
  fullnameOverride: influxdb
  enabled: false
mosquitto:
  enabled: false
  fullnameOverride: mosquitto
postgresql:
  enabled: true
  fullnameOverride: postgresql
  << : *postgresqlValues
