#Domain variables set for a local install
placeDomain: "localhost"
customRedirectPort: 8443

#  Used to set the user password in PostgresQL if enabled then passed to multiple containers in a k8s secret
xpostgresPassword: &pgPassword "{{ postgresqlPassword }}"

#  Used to set the admin "postgres" user password in PostgresQL if enabled
xpostgresPostgresPassword: &pgPostgresPassword "{{ postgresqlPostgresPassword }}"

# xsmtpPassword. the smtp password used by triggers
xsmtpPassword: &smtpPassword "{{ smtpPassword | default( '', true ) }}"

# xplaceServerSecret for the placeos service
xplaceServerSecret: &placeServerSecret "{{ placeServerSecret | default( '', true ) }}"

# xplaceServerSecret for the placeos service
xauthSecretKeyBase: &authSecretKeyBase "{{ authSecretKeyBase | default( '', true ) }}"

# xplacePassword. The value used by the init subchart to set the default domain users password
xplacePassword: &placePassword "{{ placePassword | default( '', true ) }}"

# xserverSecret for the dispatch service
xserverSecret: &serverSecret "{{ serverSecret | default( '', true ) }}"

# xelasticClientEnv configmap values for ElasticSearch Service exposed as environment variables to PlaceOS containers
xelasticClientEnv: &elasticClientEnv
  ES_HOST: "{{ elasticsearch_release_name }}.{{ elasticsearch_namespace }}"
  ES_PORT: 9200

# xetcdClientEnv configmap values for Etcd end point Service as environment variables to PlaceOS containers
xetcdClientEnv: &etcdClientEnv
  ETCD_HOST: "etcd-headless.{{ etcd_namespace }}"
  ETCD_PORT: 2379

# xredisClientEnv configmap values for the redis Service exposed as environment variables to PlaceOS containers
xredisClientEnv: &redisClientEnv
  REDIS_URL: "redis://redis-headless.{{ redis_namespace }}:6379"

xpostgresValues: &postgresValues
  postgresql:
    username: &pgUsername placeos
    database: &pgDatabase placeos
    password: *pgPassword
    postgresPassword: *pgPostgresPassword
    maxConnections: 500
    replicaCount: 1
  pgpool:
    numInitChildren: 500

xpostgresClientEnv: &postgresClientEnv
  PG_DB: *pgDatabase
  PG_HOST: postgresql-pgpool
  PG_PORT: 5432
  PG_USER: *pgUsername
  PG_QUERY: "?initial_pool_size=10&max_idle_pool_size=10"

xpostgresClientSecrets: &postgresClientSecrets
  PG_PASSWORD: *pgPassword

xinfluxClientEnv: &influxClientEnv
  INFLUX_HOST: http://influx:8086
  INFLUX_ORG: PlaceOS
  INFLUX_BUCKET: placeos

xinfluxAdminToken: &influxAdminToken "{{ influxdbAdminToken }}"

# xsmtpClientSecrets secrets values exposed as environment variables for the trigger service
xsmtpClientSecrets: &smtpClientSecrets
  SMTP_PASS: *smtpPassword

# dispatchSecrets secret values exposed as environment variables for the dispatch service
xdispatchSecrets: &dispatchSecrets
  SERVER_SECRET: *serverSecret

placeos:
  enabled: true
  # api is the overide configuration for the embedded api subchart
  api:
    configmap:
      # Service Hosts
      << : *elasticClientEnv
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *postgresClientEnv
    secrets:
      << : *postgresClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # auth is the overide configuration for the embedded auth subchart
  auth:
    configmap:
      << : *postgresClientEnv
    secrets:
      SECRET_KEY_BASE: *authSecretKeyBase
      << : *postgresClientSecrets
  # core is the overide configuration for the embedded core subchart
  core:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *postgresClientEnv
    secrets:
      << : *postgresClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # dispatch is the overide configuration for the embedded dispatch subchart
  dispatch:
    secrets:
      << : *dispatchSecrets
  # frontend-loader is the overide configuration for the embedded frontend-loader subchart
  frontendloader:
    httpSidecar: true
    configmap:
      << : *postgresClientEnv
    secrets:
      << : *postgresClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # search-ingest is the overide configuration for the embedded search-ingest subchart
  searchingest:
    configmap:
      # Service Hosts
      << : *postgresClientEnv
      << : *elasticClientEnv
    secrets:
      << : *postgresClientSecrets
  # triggers is the overide configuration for the embedded triggers subchart
  triggers:
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *postgresClientEnv
    secrets:
      << : *postgresClientSecrets
      << : *smtpClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
  # init is the overide configuration for the embedded init subchart
  init:
    config:
      # Service Hosts
      << : *postgresClientEnv
      << : *elasticClientEnv
      << : *postgresClientSecrets
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
  # staff is the overide configuration for the embedded staff subchart
  staff:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
    secrets:
      PLACE_PASSWORD: *placePassword
      PLACE_SERVER_SECRET: *placeServerSecret
    << : *postgresqlValues
  # source is the overide configuration for the embedded source subchart
  source:
    configmap:
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *postgresClientEnv
      << : *influxClientEnv
    secrets:
      << : *postgresClientSecrets
      PLACE_SERVER_SECRET: *placeServerSecret
      INFLUX_API_KEY: *influxAdminToken
    serviceAccount:
      name: null
  global:
    placeDomain: "{{ placeDomain }}"
    customRedirectPort: "{{ customRedirectPort | default( omit ) }}"

###########################################
##### Third Party Supporting Services #####
###########################################

ingress-nginx:
  enabled: false
etcd:
  fullnameOverride: etcd
  enabled: true
  auth:
    rbac:
      create: false
  persistence:
    enabled: true
    size: 100M
elasticsearch:
  enabled: true
  master:
    replicas: 1
    persistence:
      size: 100Mib
  data:
    replicas: 1
    persistence:
      size: 100Mib
  coordinating:
    replicas: 0
redis:
  enabled: true
  fullnameOverride: redis
  auth:
    enabled: false
  architecture: standalone
  commonConfiguration: |-
    notify-keyspace-events Kg$
  master:
    persistence:
      enabled: true
      size: 100M
influxdb:
  fullnameOverride: influxdb
  enabled: true
  auth:
    admin:
      token: *influxAdminToken
mosquitto:
  enabled: false
  fullnameOverride: mosquitto
postgresql-ha:
  enabled: true
  fullnameOverride: postgresql
  << : *postgresValues
