apiVersion: v2
name: frontend-loader
description: A PlaceOS helm chart for the Frontends component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-1.2202.2
