---
# tasks file for placeos.helm.releasevars
- name: check release current state
  community.kubernetes.helm_info:
    name: "{{ chart_release_name }}"
    release_namespace: "{{ checkvars[ 'chart_release_namespace' ] }}"
  register: release_state

- name: "get the existing release var"
  set_fact:
    parsed: "{{ release_state.status[ 'values' ] }}"
  when:
    - release_state.status is defined

- name: "get the existing release var for {{ item }}"
  set_fact:
    "{{ item }}": "{{ parsed[ item ] }}"
  when:
    - parsed[ item ] is defined
  loop: "{{ checkvars[ 'chart_release_vars' ] }}"