apiVersion: v2
name: triggers
description: A PlaceOS helm chart for the Triggers component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-1.2207.0