---
- hosts: k8s
  connection: local
  gather_facts: yes
  become: false
  #vars:
  #  chart_release_name: "dev"

  pre_tasks:
  - name: set passwords for services
    set_fact:
      placeServerSecret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=64') }}"
      authSecretKeyBase: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=64') }}"
      serverSecret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"
      placePassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"
      rethinkdbPassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"
      postgresqlPassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits') }}"

  roles:
  ## Override random rethinkdbPassword if it already exists
  - role: placeos.helm.releasevars
  ## Deploy Nginx Ingress Controller
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://kubernetes.github.io/ingress-nginx"
      chart_ref: "ingress-nginx"
      chart_release_namespace: "{{ ingress_nginx_namespace }}"
      chart_release_name: "{{ ingress_nginx_release_name }}"
      chart_version: "{{ ingress_nginx_chart_version }}"
  ## Deploy Ectd
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: "etcd"
      chart_release_namespace: "{{ etcd_namespace }}"
      chart_release_name: "{{ etcd_release_name }}"
      chart_version: "{{ etcd_chart_version }}"
  ## Deploy ElasticSearch
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: "elasticsearch"
      chart_release_namespace: "{{ elasticsearch_namespace }}"
      chart_release_name: "{{ elasticsearch_release_name }}"
      chart_version: "{{ elasticsearch_chart_version }}"
  ## Deploy Redis Db
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: "redis"
      chart_release_namespace: "{{ redis_namespace }}"
      chart_release_name: "{{ redis_release_name }}"
      chart_version: "{{ redis_chart_version }}"
  ## Deploy Influx Db
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: "influxdb"
      chart_release_namespace: "{{ influxdb_namespace }}"
      chart_release_name: "{{ influxdb_release_name }}"
      chart_version: "{{ influxdb_chart_version }}"
  ## Deploy Mosquitto MQTT server
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://halkeye.github.io/helm-charts/"
      chart_ref: "mosquitto"
      chart_release_namespace: "{{ mosquitto_namespace }}"
      chart_release_name: "{{ mosquitto_release_name }}"
      chart_version: "{{ mosquitto_chart_version }}"
  ## Deploy Rethinkdb
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://www.pozetron.com/helm/"
      chart_ref: "rethinkdb"
      chart_release_namespace: "{{ rethinkdb_namespace }}"
      chart_release_name: "{{ rethinkdb_release_name }}"
      chart_version: "{{ rethinkdb_chart_version }}"
  ## Deploy Postgresql
  - role: placeos.helm.thirdparty
    vars:
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: "postgresql"
      chart_release_namespace: "{{ postgresql_namespace }}"
      chart_release_name: "{{ postgresql_release_name }}"
      chart_version: "{{ postgresql_chart_version }}"
  ## Deploy PlaceOS resources
  - role: placeos.helm
    vars:
      placeos_chart_ref: "{{ playbook_dir }}/../charts/placeos/"
      chart_release_name: "placeos"
      ingress_service_name: "ingress-nginx-controller"
      ingress_namespace: "{{ ingress_nginx_namespace | default( omit ) }}"
