apiVersion: v2
name: auth
description: A PlaceOS helm chart for the Auth component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-1.2109.0

