apiVersion: v2
name: search-ingest
description: A PlaceOS helm chart for the Rubber-Soul component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-1.2202.2
