apiVersion: v2
name: dispatch
description: A PlaceOS helm chart for the Dispatch component

type: application

version: 0.1.0

# This number is reflected in the container version deployed
appVersion: placeos-2.2404.2

